name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  firmware:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build
            command: build
            args: --release
          - name: Format
            command: fmt
            args: --all -- --check --color always
          - name: Clippy
            command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build python3-venv
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.7
        with:
          default: true
          buildtargets: esp32c3
          ldproxy: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.command }} ${{ matrix.args }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: host-tests
      - name: Run tests
        run: bash test.sh
